data <- read.table("household_power_consumption.txt",sep=";",header=TRUE,colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings="?")
datafinal <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007",]
datafinal$Date = as.Date(datafinal$Date, "%d/%m/%Y")
datafinal$Time = as.POSIXlt(datafinal$Time, "%H:%M:%S")
timelist <- strptime(paste(datafinal$Date,datafinal$Time), "%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(timelist,datafinal$Global_active_power,ylab="Global Active Power",xlab="",type="l")
plot(timelist,datafinal$Voltage,ylab="Voltage",xlab="datetime",type="l")
plot(timelist,datafinal$Sub_metering_1,ylab="Energy sub metering",xlab="",type="l",col="black")
points(timelist,datafinal$Sub_metering_2,type="l",col="red")
points(timelist,datafinal$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1,cex=0.9,bty="n")
plot(timelist,datafinal$Global_reactive_power,ylab="Global_reactive_power",xlab="datetime",type="l",lwd=0.1)
dev.off()
